version: '2'
services:
  es-master:
    image:  elasticsearch:6.8.0
    container_name: es-master
    hostname: elasticsearch
    restart: always
    volumes:
      - ./es-master/data:/usr/share/elasticsearch/data:rw
      - ./es-master/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es-master/logs:/user/share/elasticsearch/logs:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #specific es java memory
    mem_limit: 1g # memory limit

  es-node1:
    image:  elasticsearch:6.8.0
    container_name: es-node1
    hostname: es-node1
    restart: always
    volumes:
      - ./es-node1/data:/usr/share/elasticsearch/data:rw
      - ./es-node1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es-node1/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #specific es java memory
    mem_limit: 1g # memory limit
  es-node2:
    image:  elasticsearch:6.8.0
    container_name: es-node2
    hostname: es-node2
    restart: always
    volumes:
      - ./es-node2/data:/usr/share/elasticsearch/data:rw
      - ./es-node2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es-node2/logs:/user/share/elasticsearch/logs:rw
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #specific es java memory
    mem_limit: 1g # memory limit
  es-head:
      image: tobias74/elasticsearch-head:6
      container_name: es-head
      restart: always
      ports:
      - "9100:9100"

  # kibana:
  #   image: kibana:6.8.0
  #   container_name: kibana
  #   hostname: kibana
  #   ports:
  #     - 5601:5601
  #   links:
  #     - es-master:elasticsearch
  #   depends_on:
  #     - es-master
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200

  skywalking:
      image: yakun0622/skywalking:6.0.1
      container_name: skywalking
      hostname: skywalking
      ports:
        - 10800:10800
        - 11800:11800
        - 12800:12800
        - 8090:8080
      volumes:
        - ./skywalking/application.yml:/app/skywalking/config/application.yml
      links:
        - es-master:es-master
        - es-node1:es-node1
        - es-node2:es-node2
      depends_on:
        - es-master
        - es-node1
        - es-node2