cluster.name: "es-cluster"
node.name: node1
node.master: false
node.data: true
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
discovery.zen.ping.unicast.hosts: ["es-master:9300", "es-node1:9300", "es-node2:9300"]

path.logs: /usr/share/elasticsearch/logs